version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - 8080:80

  backend:
    build:
      context: ./backend
    ports:
      - 3001:3001
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=db
      - PORT=3001
      - FRONTEND_PORT=8080
    depends_on:
      - mysql
  
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db

volumes:
  mysql-data: