version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src:ro
      - front-notused:/app/node_modules
    environment:
      - REACT_APP_BACKEND_PORT=3001

  backend:
    build:
      context: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend/src:/app/src:ro
      - back-notused:/app/node_modules
    command: npm run dev
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=db
      - PORT=3001
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db

volumes:
  front-notused:
  back-notused:
  mysql-data: