version: "3.8"
services:
  react-app:
    build:
      context: ./frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src:ro
    env_file:
      - ./frontend/.env